\input texinfo @c -*-texinfo-*-
@c %**start of header
@include misc/settings.texinfo
@include misc/copying.texinfo
@c %**end of header

@titlepage
   @title @value{bookletTitle}
   @subtitle Craft your own Morph
   @* @* @* @*

   @bookQuote
   @author @value{writers}

@iftex
   @page
   @vskip 0pt plus 1filll       
   @insertcopying
@end iftex
@end titlepage

@iftex
   @contents
@end iftex

@node Top

@bookQuote

@*

Deep inside Morph

@top @value{bookletTitle}

@ifnottex
  @shortcontents
  @insertcopying
  @contents
@end ifnottex

@tex
\global\parskip=0.5em
@end tex

@c=====================================
@c Chapters
@c=====================================
@include chapter-01/contents.texinfo
@c=====================================
@c Apprendices
@c=====================================
@c Copyrighted document used in the booklet
@include misc/copyrights.texinfo
@c List of exercises
@node The Exercises
@appendix The Exercises
@listoffloats Exercise
@c Solutions of exercises
@include chapter-50/contents.texinfo
@c List of examples
@node The Examples
@appendix The Examples
@listoffloats Example
@c List of figures
@node The Figures
@appendix The Figures
@listoffloats Figure
@c Indexes
@node Indexes
@appendix Conceptual index
@printindex cp
@c=====================================

@c:END OF THE BOOKLET
@bye
