@node Solutions to the Exercises
@appendix Solutions to the Exercises

@menu
* Chapter 1 (Solutions)::
@end menu

@node Chapter 1 (Solutions)
@unnumberedsec Chapter 1
@c @subheading @ref{exeSolution}
The solutions of the exercises of the booklet are authored in the file @file{chapter-50/contents.texinfo}.
